anguage: node_js

node_js: stable

cache:
  directories:
  - node_modules
before_install:

  - npm install -g hexo-cli

install:
  - npm install

script:
  - git submodule update
  - hexo g 

after_script:
  - cd ./public
  - git init
  - git config user.name "lzhbhlrpython"
  - git config user.email "Liubaolin20070125@outlook.com"
  - git add .
  - git commit -m "TravisCI Auto Deploy"
  # Github Pages
  - git push --force --quiet "https://${TOKEN}@${GH_REF}" master:master

env:
  global:
    - GH_REF: github.com/lzhbhlrpython/lzhbhlrpython.github.io.git
  
notifications:
  email:
    - Liubaolin20070125@outlook.com
  on_success: change
  on_failure: always


