# 头部菜单，title: link
menu:
  首页: /
  分类: /categories
  标签: /tags
  归档: /archives  
  关于: /about

# 是否显示目录
TOC: true

# 是否自动播放音乐
autoplay: false

# 默认音乐（随机播放）
mp3: 
    - http://music.163.com/song/media/outer/url?id=1820130405
    - http://music.163.com/song/media/outer/url?id=1452420319
      - http://music.163.com/song/media/outer/url?id=1812281737
      - http://music.163.com/song/media/outer/url?id=1811126479
      - http://music.163.com/song/media/outer/url?id=1394993941
      - http://music.163.com/song/media/outer/url?id=1814327138
      - http://music.163.com/song/media/outer/url?id=1480711777
      - http://music.163.com/song/media/outer/url?id=1820130405
      - http://music.163.com/song/media/outer/url?id=1814327138
      - http://music.163.com/song/media/outer/url?id=1452420319
       - http://music.163.com/song/media/outer/url?id=1458958359
      - http://music.163.com/song/media/outer/url?id=1394993941
      - http://music.163.com/song/media/outer/url?id=1458958359
      - http://music.163.com/song/media/outer/url?id=1814327138
      - http://music.163.com/song/media/outer/url?id=1394993941
      - http://music.163.com/song/media/outer/url?id=1820130405
      - http://music.163.com/song/media/outer/url?id=1480711777
      - http://music.163.com/song/media/outer/url?id=1820130405
      - http://music.163.com/song/media/outer/url?id=1394993941
      - http://music.163.com/song/media/outer/url?id=1811126479
    
# 首页封面图, 为空时取文章的cover作为封面(注意跨域问题,建议使用同源图片)
welcome_cover: https://tva3.sinaimg.cn/large/0072Vf1pgy1foxlom31vmj311s1hc4k5.jpg

# 默认文章封面图（随机调用,支持外链）
cover: 
    - https://tva2.sinaimg.cn/large/0072Vf1pgy1foxkfkejbbj31hc0u0k7e.jpg
    - https://tva1.sinaimg.cn/large/0072Vf1pgy1foxkd4129ej31hc0u0h5a.jpg
    - https://tva2.sinaimg.cn/large/0072Vf1pgy1foxkeyolv6j31kw0w07v2.jpg
    - https://tva4.sinaimg.cn/large/0072Vf1pgy1foxlhmfkr6j31hc0u04gi.jpg
    - https://tva2.sinaimg.cn/large/0072Vf1pgy1foxk7okxe5j31hc0u0nhp.jpg
    - https://tva3.sinaimg.cn/large/0072Vf1pgy1foxliaky92j31kw0w0b16.jpg
    - https://tva3.sinaimg.cn/large/0072Vf1pgy1foxkc9gjl2j31hc0u0h7m.jpg
    - https://tva1.sinaimg.cn/large/0072Vf1pgy1foxkipc63ij31hc0u0wv2.jpg
    - https://tva1.sinaimg.cn/large/0072Vf1pgy1foxk6x3lejj31kw0w0x5a.jpg
    - https://tva3.sinaimg.cn/large/0072Vf1pgy1fodqn2e7bvj318g0p0qv5.jpg
 
# 是否使用mathjax
mathjax: true


# 是否关闭默认滚动条
scrollbar: true

# 本地搜索,请将索引文件放在网站根目录,或修改主题js文件的path值
local_search:
    # 是否启用
    enable: false

# 是否显示 一言(hitokoto)
hitokoto: true

# 链接(可选:facebook,twitter,github,wechat,email)
links:
    facebook: /
    twitter: https://twitter.com/PythonicL
    github: https://github.com/lzhbhlrpython
    wechat: /
    email: mailto:Barry.Coder.Liu@aliyun.com
  
# 备案
beian: 
    # 是否显示备案信息
    enable: false
    # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
    enableFooter: false
    # 备案号
    beianInfo: 冀ICP备xxxxxxx号
    # 链接地址
    link: http://www.beian.miit.gov.cn

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否启用评论功能
    enable: false
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: ''
    # 应用秘钥
    clientSecret: ''
    # issue仓库名
    repo: ''
    # Github名
    owner: ''
    # Github名
    admin: ['']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: Blog

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
