name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Hexo Auto Deploy
      # You may pin to the exact commit or the version.
      # uses: bluekrow/hexo-auto-deploy@7aadc9941b256fba49ba35e649d74e3296345f3d
        uses: bluekrow/hexo-auto-deploy@v1.1.0
        with:
          # Github secret token that grants access to the destination repository. If the detination repository is the same local repositroy, the token can be obtained using \$\{\{ secrets.GITHUB_TOKEN \}\}
          token: ${{ secrets.ACCESS_TOKEN }}
          # Destination repository name. If not specified the default value is the local repository name
          repo_name: lzhbhlrpython.github.io # optional, default is ${{ github.EVENT.REPOSITORY.NAME }}
          # Destination repository owner name. If not specified the default value is the local repository owner name
          owner_name: lzhbhlrpython # optional, default is ${{ github.EVENT.REPOSITORY.OWNER.NAME }}
          # Destination repository owner email. If not specified the default value is the local repository owner email
          owner_email: Liubaolin20070125@outlook.com # optional, default is ${{ github.EVENT.REPOSITORY.OWNER.EMAIL }}
          # Commit message which originated this action execution. If specified, the commit message will be overridden
          commit_message: ACTION # optional, default is ${{ github.EVENT.HEAD_COMMIT.MESSAGE }}
          # Destination deploy branch. If not specified the default value is "gh-pages"
          deploy_branch: master # optional, default is gh-pages
          # Local deploy directory to link to the remote repository and branch. If not specified the default value is ".deploy"
          deploy_dir: .deploy # optional, default is .deploy
          # Local source directory, where the static content has been generated. If not specified the default value is "public"
          source_dir: public # optional, default is public
