name: CI

on:
  push:
    branches:
      - master

env:
  GIT_USER: lzhbhlrpython
  GIT_EMAIL: liubaolin20070125@outlook.com
  THEME_REPO: Fechin/hexo-theme-diaspora
  THEME_BRANCH: master
  DEPLOY_REPO: lzhbhlrpython/lzhbhlrpython.github.io
  DEPLOY_BRANCH: master

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12.x]

    steps:
      - name: Hexo Action with Nodejs v14.15.5 LTS
        # You may pin to the exact commit or the version.
        # uses: mark0smith/hexo-action@522dd860321f4f9f8f3861b1e9199ba1246a0b7e
        uses: mark0smith/hexo-action@v0.0.1
        with:
          # Github user name
          user_name: github-actions[bot] # default is github-actions[bot]
          # Github email
          user_email: 41898282+github-actions[bot]@users.noreply.github.com # default is 41898282+github-actions[bot]@users.noreply.github.com
          # The deploy key for Github Pages repo
          deploy_key: Action # default is 
          # Git commit messages to your GitHub Pages repository.
          commit_msg: Deploy-Action # optional, default is 
