name: CI

on:
  push:
    branches:
      - master

env:
  GIT_USER: lzhbhlrpython
  GIT_EMAIL: liubaolin20070125@outlook.com
  THEME_REPO: Fechin/hexo-theme-diaspora
  THEME_BRANCH: master
  DEPLOY_REPO: lzhbhlrpython/lzhbhlrpython.github.io
  DEPLOY_BRANCH: master

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12.x]

    steps:
      - name: hexo_action
      # You may pin to the exact commit or the version.
  # uses: esphere-dumal/hexo_action@c2dbd777c96dd3107f412c22e9d069a61cceba76
        uses: esphere-dumal/hexo_action@1.0.0
        with:
          # github username
          user_name: github_action # default is github_action
          # github user_email
          user_email: github_action@github.com # default is github_action@github.com
          # the deploy key for repo
          deploy_key: 9QEEvE0jiQRDFRel6p8x8YbeT8frlAWRZqwTnlsC+T4 # default is 
          # commit messages for repo
          commit_msg: ACTION-DEPLOY # optional, default is 
